import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/bars/navbar/navbar";
import AnnouncementBar from "@/components/bars/announcement-bar";

const poppins = Poppins({
  subsets: ['latin', 'latin-ext'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}`}
      >
        <header className="sticky top-0 left-0 z-50 bg-white">
          <AnnouncementBar />
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
